config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'
  get 'about' => 'homes#about'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show]
  get 'unsubscribe/' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  patch ':id/withdraw/' => 'users#withdraw', as: 'withdraw_user'
  put 'withdraw/' => 'users#withdraw'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/continent.rb
class Continent < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :continent
  attachment :image
  
  validates :country, :city, :flight, presence: true, length: { maximum: 20 }
  validates :image, :from_date, :to_date, :continent_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  
  BEGINNER = "紙ひこうき️"
  EXPERT = "ヘリコプター"
  MASTER = "ジェット機️"
  GRAND_MASTER = "ロケット"
  LEGEND = "スペースシップ"
  CAN_GET_BADGE = 2

  @continents = Continent.all

  has_secure_password validations: true
  validates :email, presence: true, uniqueness: true

  has_many :posts, dependent: :destroy

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end

  # ユーザーのレベルをチェックするメソッド
  def self.level_check(all_posts_count)
    case all_posts_count
    when 0..10
      @level = BEGINNER
    when 11..20
      @level = EXPERT
    when 21..30
      @level = MASTER
    when 31..40
      @level = GRAND_MASTER
    when 41..nill
       @level = LEGEND
    else
      @level = "レベルが読み込めませんでした"
    end
  end

  # 各エリアの投稿数をカウントし、バッジのあるエリアを配列でリターン
  def self.badge_check(user_posts)
    @has_area_badge = []
    for continent_id in 2..9 do
      area_count = user_posts.where(continent_id: continent_id).count
      if area_count >= CAN_GET_BADGE
        @has_area_badge.push(@continents.find(continent_id).name)
      end
    end
    @has_area_badge
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :current_user
  before_action :require_sign_in!, except: [:top, :about]
  helper_method :signed_in?

  protect_from_forgery with: :exception
  
  def current_user
    remember_token = User.encrypt(cookies[:user_remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:user_remember_token] = remember_token
    user.update!(remember_token: User.encrypt(remember_token))
    @current_user = user
  end

  def sign_out
    @current_user = nil
    cookies.delete(:user_remember_token)
  end
  
  def signed_in?
    @current_user.present?
  end
  
  private
  
  def require_sign_in!
    redirect_to login_path unless signed_in?
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @continents = Continent.all
    if params[:continent_id]
      @continent = @continents.find(params[:continent_id])
      @posts = @continent.posts.where(user_id: current_user.id).page(params[:page]).per(6)
    else
      @posts = current_user.posts.page(params[:page]).per(6).order(id: "DESC")
    end
    @all_posts_count = @posts.total_count
  end

  def show
    @post = Post.find(params[:id])
    redirect_to users_path unless current_user == @post.user
  end

  def new
    @post = Post.new
    @continent_list = Continent.pluck('name, id')
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id), notice: "コレクションに追加しました。"
    else
      @continent_list = Continent.pluck('name, id')
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @continent_list = Continent.pluck('name, id')
    if @post.user.id == current_user.id
      render :edit
    else
      redirect_to :posts_path
    end
  end
  
  def update
    @post = Post.find(params[:id])
    @continents = Continent.all
    if @post.update(post_params)
      redirect_to post_path(@post.id), notice: '投稿を編集しました。'
    else
      @continent_list = Continent.pluck('name, id')
      render :edit
    end
  end
  
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:image, :country, :city, :continent_id, :from_date, :to_date, :flight, :memo)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_sign_in!, only: [:new, :create]
  before_action :validate_user, only: [:create]
  
  def new
  end

  def create
    if @user.authenticate(session_params[:password])
      sign_in(@user)
      redirect_to users_path
    else
      flash[:danger] = 'メールアドレスまたはパスワードが正しくありません'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  # 退会済みのユーザーをブロック
  def validate_user
    @user = User.find_by!(email: session_params[:email])
    if @user.is_valid == false
      reset_session
      redirect_to signup_path
    end
  rescue
    flash.now[:danger] = 'メールアドレスまたはパスワードが正しくありません'
    render action: 'new'
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_sign_in!, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to users_path
    else
      render "new"
    end
  end

  def index
    @continents = Continent.all
  end

  def show
    user_posts = current_user.posts
    all_posts_count = user_posts.count
    @user_level = User.level_check(all_posts_count)
    @completed_badges = User.badge_check(user_posts)
  end
  
  def unsubscribe
    @user = current_user
  end

  def withdraw
    @user = current_user
    @user.update(is_valid: false)
    sign_out
    flash[:notice] = "退会しました。"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-12">
      <div class="about-title">
        <h1>About</h1>
      </div>
      <div class="about-top mt-5">
        <h4>楽しかった旅行の思い出を記録して、自分のトラベルコレクションを作りましょう！</h4>
      </div>
      <div class="about-text mt-5">
        <p>トラバムはあなたの旅行のベストモーメントを記録するフォトアルバムアプリです。</p>
        <p>
        お気に入り写真を一つだけ選ぶことで、<br>旅行中に撮った多数の写真をアップロードするのに時間がかかるから、<br>
        と思い出記録をするのをつい忘れてしまうような方でも<br>「トラバム」でならさっと気軽に記録ができます。
        </p>
        <p>投稿数を増やしてトラベラーレベルを上げたり、エリアごとのバッジをもらえたりと楽しい機能も満載。</p>
        <p>今すぐ使ってみましょう！</p>
        <p>Happy traveling~</p>
      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
       <div class="top-image">
        <div class="top-image-button">
          <%= link_to "新規登録", signup_path, class: "btn btn-primary nav-signup btn-lg" %>
          <%= link_to "ログイン", login_path, class: "btn btn-primary nav-signup btn-lg" %>
        </div>
      </div>
    </div>
  </div>

<div class="container">
  <div class="row">
    <div class="col-md-4 how-to-use-block">
      <h2>使い方</h2>
      <p>投稿画面であなたの旅行を記録しましょう！</p>
      <p>
        旅行中のベストショットと<br>日程や便名、<br>
        思い出メモに訪れた場所や宿泊したホテル、<br>レストランなどを記入。<br>
      </p>
      <p>
        保存後はエリアごとに閲覧ができます。<br>
      </p>
      <p>旅行するたびトラバムに記録し、<br>どんどんレベルを上げていきましょう！</p>
      <p>コレクションが増えれば<br>エキスパートバッジももらえるかも！？</p>
    </div>
    
    <div class="col-md-4 how-to-use-block">
      <h2>レベル</h2>
      <p>投稿数が増えるにつれて<br>あなたのトラベラーレベルが上がります</p>
      <table class="table">
        <tbody>
          <tr>
            <th>1~10</th>
            <td>紙ひこうき</td>
          </tr>
          <tr>
            <th>1~20</th>
            <td>ヘリコプター</td>
          </tr>
          <tr>
            <th>1~30</th>
            <td>ジェット機</td>
          </tr>
          <tr>
            <th>1~40</th>
            <td>ロケット</td>
          </tr>
          <tr>
            <th>41~</th>
            <td>スペースシップ</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="col-md-4 how-to-use-block">
      <h2>バッジ</h2>
      <p>一つのエリアに５つ以上※の投稿で<br>バッジがもらえます</p>
      <table class="table">
        <tbody>
          <tr>
            <th>日本</th>
            <td>さくらバッジ</td>
          </tr>
          <tr>
            <th>アジア</th>
            <td>お米バッジ</td>
          </tr>
          <tr>
            <th>オセアニア</th>
            <td>ワラビーバッジ</td>
          </tr>
          <tr>
            <th>ヨーロッパ</th>
            <td>キャッスルバッジ</td>
          </tr>
          <tr>
            <th>中東</th>
            <td>アラジンバッジ</td>
          </tr>
          <tr>
            <th>アフリカ</th>
            <td>サファリバッジ</td>
          </tr>
          <tr>
            <th>北米</th>
            <td>ベアーバッジ</td>
          </tr>
          <tr>
            <th>南米</th>
            <td>アマゾンバッジ</td>
          </tr>
        </tbody>
      </table>

      <p class=small>
        ※現在は開発段階のため<br>２つ以上の投稿でバッジがもらえるようになっています。
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trabum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Google fonts CDN-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol:wght@500&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <h2><%= link_to 'トラバム', root_path, class: 'nav-link text-dark logo' %></h2>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav ml-auto ">
            <% if signed_in? %>
              <li class="nav-item ">
                <%= link_to "ホーム", users_path, class: 'fas fa-home nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "アルバム", posts_path, class: "fas fa-book nav-link text-dark" %>
              </li>
              <li class="nav-item">
                <%= link_to "新規投稿", new_post_path, class: "fas fas fa-camera nav-link text-dark" %>
              </li>
              <li class="nav-item">
                <%= link_to "マイページ", user_path(@current_user), class: "fas fa-user nav-link text-dark" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト",logout_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-dark" %>
              </li>
            <% else %>
              <li class="nav-item ">
                <%= link_to "ホーム", root_path, class: "fas fa-home nav-link text-dark" %>
              </li>
              <li class="nav-item ">
                <%= link_to "アバウト", about_path, class: "fas fa-link nav-link text-dark" %>
              </li>
              <li class="nav-item ">
                <%= link_to "新規登録", signup_path, class: "fas fa-user-plus nav-link text-dark" %>
              </li>
              <li class="nav-item ">
                <%= link_to "ログイン", login_path, class: "fas fa-sign-in-alt nav-link text-dark" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <main>
      <!--フラッシュメッセージ-->
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <%= yield %>
    </main>
    <footer>
      <p class="footer-text">© 2021 Yukino Shinji</p>
    </footer>
  </body>
</html>

app/views/posts/edit.html.erb
<!--エラーメッセージ-->
<% if @post.errors.any? %>
  <div class="container">
    <h5 class=text-danger><%= @post.errors.count %>件のエラーが発生しました</h5>
    <ul class="ml-4">
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container mt-3">
  <div class="row">
    <div class="col-md-12">
      <h2>旅行を編集</h2>
      <%= form_with model: @post, local:true do |f| %>
        <div class="form">
          <div class="form-group">
            <%= f.label :写真 %><br/>
            <%= f.attachment_field :image %>
          </div>
          <div class="form-group">
            <%= f.label :国名 %><br/>
            <%= f.text_field :country, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :都市名 %><br/>
            <%= f.text_field :city, class:"form-control" %>
          </div>
          <div class="form-group mb-4">
            <%= f.label :エリア %><br/>
            <%= f.select :continent_id, @continent_list, include_blank: "選択してください" %>
          </div>
          <div class="form-group">
            <%= f.label :日付 %><br/>
            <%= f.date_field :from_date %>から<%= f.date_field :to_date %>まで<br/>
          </div>
          <div class="form-group">
            <%= f.label :便名 %><br/>
            <%= f.text_field :flight, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :思い出メモ%><br/>
            <%= f.text_area :memo, class:"form-control" %>
          </div>
        </div>
        <div class="create-btn">
          <%= f.submit '編集保存', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <h5 class="text-center">エリア検索</h5>
      <div class="area">
        <%= link_to "全エリア", posts_path, class: "btn btn-primary" %>
        <% @continents.each do |continent| %>
        <div class="area-button">
          <%= link_to continent.name, posts_path(continent_id: continent.id), class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md-12">
      <div class="post-title">
        <% if params[:continent_id] %>
          <h3><%= @continent.name %> (<%= @all_posts_count %>)</h3>
        <% else %>
          <h3>全投稿 (<%= @all_posts_count %>)</h3>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 post-items">
      <% @posts.each do |post| %>
        <div class="items">
          <%= link_to post_path(post.id) do %>
            <%= attachment_image_tag post,:image, class: "photo", fallback: "no_image.jpg" %>
            <div class="item-text">
              <h4><%= post.country %>・<%= post.city %></h4>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= paginate @posts %>

app/views/posts/new.html.erb
<!--エラーメッセージ-->
<% if @post.errors.any? %>
  <div class="container">
    <h5 class=text-danger><%= @post.errors.count %>件のエラーが発生しました</h5>
    <ul class="ml-4">
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container mt-3">
  <div class="row">
    <div class="col-md-12">
      <h2>旅行を追加</h2>
      <%= form_with model: @post, local:true do |f| %>
        <div class="form">
          <div class="form-group">
            <%= f.label :写真 %><br/>
            <%= f.attachment_field :image %>
          </div>
          <div class="form-group">
            <%= f.label :国名 %><br/>
            <%= f.text_field :country, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :都市名 %><br/>
            <%= f.text_field :city, class:"form-control" %>
          </div>
          <div class="form-group mb-4">
            <%= f.label :エリア %><br/>
            <%= f.select :continent_id, @continent_list, include_blank: "選択してください" %>
          </div>
          <div class="form-group">
            <%= f.label :日付 %><br/>
            <%= f.date_field :from_date %>から<%= f.date_field :to_date %>まで<br/>
          </div>
          <div class="form-group">
            <%= f.label :便名 %><br/>
            <%= f.text_field :flight, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :思い出メモ%><br/>
            <%= f.text_area :memo, class:"form-control" %>
          </div>
        </div>
        <div class="create-btn">
          <%= f.submit '保存', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 ">
      <%= link_to post_path(@post.id) do %>
        <%= attachment_image_tag @post,:image, class: 'img-fluid',  fallback: "no_image.jpg" %>
      <% end %>
    </div>
    <div class="col-md-4">
      <div class="post-details">
        <div class="country mb-4">
          <h3>
            <i class="fas fa-map-marker-alt"></i>
            <%= @post.country %>・<%= @post.city %>
          </h3>
        </div>
        
        <div class="flight mb-4">
          <h4>
            <i class="fas fa-plane"></i>
            <%= @post.flight %>
          </h4>
        </div>
        
        <div class="date mb-5">
          <h4>
            <i class="fas fa-clock"></i>
            <%= @post.from_date %> ~ <%= @post.to_date %>
          </h4>
        </div>
        
        <div class="date mb-5">
          <h4>思い出メモ</h4>
            <%= @post.memo %>
        </div>
      </div>

      <div class="button">
        <%= link_to "", edit_post_path, class:"fas fa-edit btn btn-lg btn-primary" %></td>
        <%= link_to "", post_path(@post),method: :delete, class:"fas fa-trash btn btn-lg btn-primary", "data-confirm" =>"本当に消しますか?" %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="map-image">
  <div class="continent">
    <% @continents.each do |continent| %>
      <div class="continent-area">
        <%= link_to continent.name, posts_path(continent_id: continent.id), class: "btn-circle-flat" %><br>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-4 mx-auto">
      <h2>新規登録</h2>
      <%= form_with model: @user, url: signup_path, local: true do |f| %>
        <div class="form-group">
          <%= f.label "名前" %><br/>
          <%= f.text_field :name, class: "form-control", autofocus: true %>
        </div>

        <div class="form-group">
          <%= f.label "メールアドレス" %><br/>
          <%= f.email_field :email, class: "form-control", autofocus: true, autocomplete: "email" %>
        </div>

        <div class="form-group">
          <%= f.label "パスワード" %>
          <%= f.password_field :password, class: "form-control", autocomplete: "new-password" %>
        </div>

        <div class="form-group">
          <%= f.label "パスワード確認" %><br/>
          <%= f.password_field :password_confirmation, class: "form-control", autocomplete: "new-password" %>
        </div>

        <div class="actions">
          <%= f.submit "登録", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-5">
      <h2>プロフィール</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>名前</th>
            <td><%= @current_user.name %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @current_user.email %></td>
          </tr>
        </thead>
      </table>
    </div>

    <div class="col-md-5 m-auto text-center">
      <h2><i class="fas fa-plane"></i>トラベラーレベル<i class="fas fa-plane"></i></h2>
      <h2><%= @user_level %></h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <input type="hidden" class="badge_array" value="<%= @completed_badges %>">
      <h2>獲得バッジ</h2>
      <div class="badge_container">
        <div class="area_badge" id="日本">
          <%= image_tag "Japan.png" %>
        </div>
        <div class="area_badge" id="アジア">
          <%= image_tag "Asia.png" %>
        </div>
        <div class="area_badge" id="オセアニア">
          <%= image_tag "Oceania.png" %>
        </div>
        <div class="area_badge" id="ヨーロッパ">
          <%= image_tag "Europe.png" %>
        </div>
        <div class="area_badge" id="中東">
          <%= image_tag "Middle_East.png" %>
        </div>
        <div class="area_badge" id="アフリカ">
          <%= image_tag "Africa.png" %>
        </div>
        <div class="area_badge" id="北米">
          <%= image_tag "North_America.png" %>
        </div>
        <div class="area_badge" id="南米">
          <%= image_tag "South_America.png" %>
        </div>
      </div>
    </div>
  </div>

   <!--退会機能-->
  <div class="row">
    <div class="col-md-12">
      <%= link_to '退会する', confirm_unsubscribe_path, class:'btn btn-primary' %>
    </div>
  </div>
  <div class="icon8-link">
      icons by <a target="_blank" href="https://icons8.com">Icons8</a>
  <div>
</div>

app/views/users/unsubscribe.html.erb
<div class = "container">
  <div class = "row">
    <div class="px-3 mx-auto mt-5">
      <h3 class="unsubscribe"><strong>本当に退会しますか？</strong></h3>
      <p class="unsubscribe">
        退会すると、<br>
        これまでの旅行が閲覧できなくなります。<br>
        退会する場合は、「退会する」をクリックしてください。<br>
      </p>
      <%= link_to '退会しない', users_path, class:'btn btn-primary offset-3' %>
      <%= link_to '退会する', withdraw_user_path(@user), method: :patch, class:'btn btn-primary' %>
    </div>
  </div>
</div>